### ISSUE TITLE
arabic issue

### ISSUE THREAD

**Issue by Ahmedsolution** [busaeed/E-InvoiceBarCode#1]
مشكور اخى الفاضل على مجهودك
لكنى وجدت مشكله مع اللغه العربية(اسم المحل او seller)
فاللغه العربيه لاسم المحل تعمل فقط داخل ال IDE ولكن لا تعمل خارجه بملف ال jar
فالإسم يظهر خارج ال IDE على هيئة علامات إستفهام (؟؟؟؟؟؟)
فهل يمكنك المساعده ولكم جزيل الشكر

**Comment by busaeed** [comment]
اكون شاكر لك لو وضحت المشكلة اكثر من خلال صور للمشكلة و مثال للمدخلات و المخرجات.
هل جربت تقرأ الباركود عن طريق E-Invoice QR reader ؟

**Comment by FlavaSava7** [comment]
> مشكور اخى الفاضل على مجهودك لكنى وجدت مشكله مع اللغه العربية(اسم المحل او seller) فاللغه العربيه لاسم المحل تعمل فقط داخل ال IDE ولكن لا تعمل خارجه بملف ال jar فالإسم يظهر خارج ال IDE على هيئة علامات إستفهام (؟؟؟؟؟؟) فهل يمكنك المساعده ولكم جزيل الشكر

@Ahmedsolution 

واجهت نفس المشكلة ، الحل بإنه تستعمل **UTF-8 Encoding**

1- عدل ال **getLength** الموجود في **Tag.java**  وخليها :
`this.value.getBytes(StandardCharsets.UTF_8).length`

2- عدل ال **toBase64** الموجود في **QRBarcodeEncoder.java** وخليها :
`Base64.getEncoder().encodeToString(tlvString.getBytes(StandardCharsets.UTF_8))`

**Comment by FlavaSava7** [comment]
@busaeed 
There is a pull request if you would like to merge the fix https://github.com/busaeed/E-InvoiceQRBarcode/pull/2
